package android.database.sqlite;
import android.content.ContentValues; import android.database.*; import java.util.*;
public class SQLiteDatabase {
 public static final int CONFLICT_REPLACE=5; private final Map<String,List<LinkedHashMap<String,Object>>> tables=new HashMap<>(); private final Map<String,Long> seq=new HashMap<>();
 public void execSQL(String sql){} public void execSQL(String sql,Object[] args){} public void beginTransaction(){} public void setTransactionSuccessful(){} public void endTransaction(){}
 private List<LinkedHashMap<String,Object>> table(String n){return tables.computeIfAbsent(n,k->new ArrayList<>());} private static void copy(ContentValues v,Map<String,Object> row){for(Map.Entry<String,Object> e:v.valueSet())row.put(e.getKey(),e.getValue());}
 public long insertOrThrow(String table,String nullHack,ContentValues values){LinkedHashMap<String,Object> row=new LinkedHashMap<>();copy(values,row);long id=values.getAsLong("_id")==null?seq.merge(table,1L,Long::sum):values.getAsLong("_id");row.put("_id",id);this.table(table).add(row);return id;}
 public long insertWithOnConflict(String table,String nullHack,ContentValues values,int conflict){if(conflict==CONFLICT_REPLACE&&"sync_queue".equals(table)){String u=values.getAsString("item_uuid"),o=values.getAsString("operation");this.table(table).removeIf(r->Objects.equals(str(r.get("item_uuid")),u)&&Objects.equals(str(r.get("operation")),o));}return insertOrThrow(table,nullHack,values);}
 public int update(String table,ContentValues values,String where,String[] args){int n=0;for(Map<String,Object> row:this.table(table))if(matches(row,where,args)){copy(values,row);n++;}return n;}
 public int delete(String table,String where,String[] args){int before=this.table(table).size();this.table(table).removeIf(r->matches(r,where,args));return before-this.table(table).size();}
 public Cursor query(String table,String[] columns,String selection,String[] args,String group,String having,String order){return query(table,columns,selection,args,group,having,order,null);} public Cursor query(String table,String[] columns,String selection,String[] args,String group,String having,String order,String limit){List<LinkedHashMap<String,Object>> found=new ArrayList<>();for(LinkedHashMap<String,Object> row:this.table(table))if(matches(row,selection,args))found.add(row); sort(found,order);if(limit!=null&&found.size()>Integer.parseInt(limit))found=new ArrayList<>(found.subList(0,Integer.parseInt(limit)));String[] cols=columns==null?allColumns(table,found):columns;MatrixCursor c=new MatrixCursor(cols);for(Map<String,Object> row:found){Object[] x=new Object[cols.length];for(int i=0;i<cols.length;i++)x[i]=row.get(cols[i]);c.addRow(x);}return c;}
 public Cursor rawQuery(String sql,String[] args){if(sql.toUpperCase(Locale.ROOT).startsWith("SELECT COUNT(*) FROM ")){String tail=sql.substring("SELECT COUNT(*) FROM ".length());String table=tail.split(" ")[0];String where=sql.toUpperCase(Locale.ROOT).contains(" WHERE ")?sql.substring(sql.toUpperCase(Locale.ROOT).indexOf(" WHERE ")+7):null;int n=0;for(Map<String,Object> row:this.table(table))if(matches(row,where,args))n++;MatrixCursor c=new MatrixCursor(new String[]{"COUNT(*)"});c.addRow(new Object[]{n});return c;}throw new UnsupportedOperationException(sql);}
 public List<Map<String,Object>> rows(String table){return Collections.unmodifiableList(new ArrayList<>(this.table(table)));}
 private String[] allColumns(String table,List<LinkedHashMap<String,Object>> found){LinkedHashSet<String> s=new LinkedHashSet<>();s.add("_id");for(Map<String,Object> r:this.table(table))s.addAll(r.keySet());return s.toArray(new String[0]);}
 private static void sort(List<LinkedHashMap<String,Object>> rows,String order){if(order==null||order.startsWith("CASE"))return;String first=order.split(",")[0].trim();String[] p=first.split("\\s+");String col=p[0];boolean desc=p.length>1&&"DESC".equalsIgnoreCase(p[1]);rows.sort((a,b)->{int c=cmp(a.get(col),b.get(col));return desc?-c:c;});}
 private static int cmp(Object a,Object b){if(a==null&&b==null)return 0;if(a==null)return -1;if(b==null)return 1;if(a instanceof Number||b instanceof Number)return Long.compare(num(a),num(b));return str(a).compareTo(str(b));}
 private static boolean matches(Map<String,Object> row,String where,String[] args){if(where==null||where.trim().isEmpty())return true;ArgIndex ai=new ArgIndex();String[] ors=where.trim().split("(?i)\\s+OR\\s+");for(String or:ors){boolean ok=true;for(String atom:or.trim().split("(?i)\\s+AND\\s+"))if(!atom(row,atom.trim(),args,ai)){ok=false;}if(ok)return true;ai.i=0;}return false;}
 private static boolean atom(Map<String,Object> row,String atom,String[] args,ArgIndex ai){atom=atom.replace("(","").replace(")","").trim();String op=null;for(String x:new String[]{"<=",">=",">","="," IS NULL"})if(atom.toUpperCase(Locale.ROOT).contains(x.trim().toUpperCase(Locale.ROOT))){op=x;break;}if(op==null)throw new UnsupportedOperationException("where: "+atom);if(" IS NULL".equals(op)){String col=atom.substring(0,atom.toUpperCase(Locale.ROOT).indexOf(" IS NULL")).trim();return row.get(col)==null;}int at=atom.indexOf(op);String col=atom.substring(0,at).trim(), rhs=atom.substring(at+op.length()).trim();Object expected;if("?".equals(rhs))expected=args[ai.i++];else if(rhs.startsWith("'")&&rhs.endsWith("'"))expected=rhs.substring(1,rhs.length()-1);else expected=rhs;Object actual=row.get(col);int c=(actual instanceof Number||numeric(expected))?Long.compare(num(actual),num(expected)):Objects.toString(actual,"").compareTo(Objects.toString(expected,""));if("=".equals(op))return c==0;if(">".equals(op))return c>0;if("<=".equals(op))return c<=0;if(">=".equals(op))return c>=0;return false;}
 private static boolean numeric(Object x){if(x==null)return false;try{Long.parseLong(String.valueOf(x));return true;}catch(Exception e){return false;}} private static long num(Object x){if(x==null)return 0;return x instanceof Number?((Number)x).longValue():Long.parseLong(String.valueOf(x));} private static String str(Object x){return x==null?null:String.valueOf(x);} private static final class ArgIndex{int i;}
}
